export default {
	name: 'map_test',
	verison: '1.0.0',

	dynamicOfGame: 200,

	entities: {
		// player: {
		// 	id: 'player',
		// 	type: 'player',
		// 	name: 'playerName',
		// 	floor: 'floor1',
		// 	chunk: 'front',
		// 	x: 2,
		// 	y: 2,
		// 	effects: {},
		// 	inventory: {},
		// 	coins: 0,
		// 	health: 4,
		// },
		enemy1: {
			id: 'enemy1',
			type: 'enemy',
			name: 'enemyName',
			floor: 'floor1',
			chunk: 'front',
			x: 4,
			y: 0,
			effects: {},
			inventory: {},
			style: '#ae39',
			coins: 10,
			health: 1,
			attack: 2,
		},
		enemy2: {
			id: 'enemy2',
			type: 'enemy',
			name: 'enemyName',
			floor: 'floor1',
			chunk: 'front',
			x: 3,
			y: 0,
			effects: {},
			inventory: {},
			style: '#ae39',
			coins: 10,
			health: 1,
			attack: 2,
		},
	},

	items: {
		potion1: {
			id: 'potion1',
			type: 'potion',
			name: 'potionName',
			floor: 'floor1',
			chunk: 'front',
			x: 5,
			y: 5,
			pickedBy: null,
			style: '#54e8',
			effects: {},
			attack: 1,
			health: 1,
		},
		potion2: {
			id: 'potion2',
			type: 'potion',
			name: 'potionName',
			floor: 'floor1',
			chunk: 'front',
			x: 3,
			y: 3,
			pickedBy: null,
			style: '#54e8',
			effects: {},
			attack: 1,
			health: 1,
		},
		sword1: {
			id: 'sword1',
			type: 'weapon',
			name: 'swordName',
			floor: 'floor1',
			chunk: 'front',
			x: 4,
			y: 4,
			pickedBy: null,
			style: 'blue',
			effects: {},
			attack: 1,
			health: 2,
		},
	},

	floors: {
		floor1: {
			name: 'floor1Name',
			size: { x: 7, y: 7, z: 7 },
			walls: {
				front: {
					style: 'default',
				},
			},
		},
	},


	styles: {
		walls: {
			'default-line': 'blue',
			'default-dot-empty': 'red',
			'default-dot-innerСorner': '/default-dot-innerСorner.png',
			'default-dot-outerСorner': '/default-dot-outerСorner.png',
			'default-dot-linear': '/default-dot-linear.png',
			'default-dot-green': '/default-dot-green.png',
		},
	},
};